[package]
name = "kite-node"
version = "2.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
nautilus-common.workspace = true
nautilus-core.workspace = true
nautilus-data.workspace = true
nautilus-model.workspace = true
chrono.workspace = true
kite-adapter = { path = "../../crates/kite-adapter" }
serde_json.workspace = true
reqwest.workspace = true
zeroize.workspace = true
tokio.workspace = true

kite-journal = { path = "../../crates/kite-journal" }

nautilus-trading.workspace = true

nautilus-live.workspace = true
async-trait.workspace = true

nautilus-persistence.workspace = true
nautilus-infrastructure.workspace = true

nautilus-sandbox.workspace = true

serde.workspace = true
redis.workspace = true
indexmap = "2"
log = "0.4"


arrow = { version = "59", default-features = false }

[dev-dependencies]
tempfile = "3"
redis.workspace = true
